<a href="https://colab.research.google.com/github/marknaman05/freecodecamp-data-analysis/blob/main/numpy_array_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

> ### **Assignment 2 - Numpy Array Operations**
>
> This assignment is part of the course ["Data Analysis with Python: Zero to Pandas"](http://zerotopandas.com). The objective of this assignment is to develop a solid understanding of Numpy array operations. In this assignment you will:
>
> 1. Pick 5 interesting Numpy array functions by going through the documentation: https://numpy.org/doc/stable/reference/routines.html
> 2. Run and modify this Jupyter notebook to illustrate their usage (some explanation and 3 examples for each function). Use your imagination to come up with interesting and unique examples.
> 3. Upload this notebook to your Jovian profile using `jovian.commit` and make a submission here: https://jovian.ml/learn/data-analysis-with-python-zero-to-pandas/assignment/assignment-2-numpy-array-operations
> 4. (Optional) Share your notebook online (on Twitter, LinkedIn, Facebook) and on the community forum thread: https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575 .
> 5. (Optional) Check out the notebooks [shared by other participants](https://jovian.ml/forum/t/assignment-2-numpy-array-operations-share-your-work/10575) and give feedback & appreciation.
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.
>
> Try to give your notebook a catchy title & subtitle e.g. "All about Numpy array operations", "5 Numpy functions you didn't know you needed", "A beginner's guide to broadcasting in Numpy", "Interesting ways to create Numpy arrays", "Trigonometic functions in Numpy", "How to use Python for Linear Algebra" etc.
>
> **NOTE**: Remove this block of explanation text before submitting or sharing your notebook online - to make it more presentable.


# Title Here


### Subtitle Here

Write a short introduction about Numpy and list the chosen functions.

Numpy is a Python library that helps us to perform mathematical calculations in python with less time complexity .

- np.array() : used to form list/array using numpy
- np.dot : used to perform dot product of two matrix
- np.matmul : to perform matrx multiplication
- np.arange(start,stop,step) : gives the range of values from start till stop-1 incremented by step
- np.linspace(start , end , count) : gives equally spaced 'count' numbers starting from start till end (end included)

The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Binder". This will run the notebook on mybinder.org, a free online service for running Jupyter notebooks.

In [ ]:
!pip install jovian --upgrade -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.6/68.6 kB 4.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done


In [ ]:
import jovian

In [ ]:
jovian.commit(project='numpy-array-operations')

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


Let's begin by importing Numpy and listing out the functions covered in this notebook.

In [ ]:
import numpy as np

In [ ]:
# List of functions explained
function1 = np.add(a1,a2)
function2 = np.subtract(a1,a2)
function3 = np.multiply(a1,a2)
function4 = np.divide(a1,a2)
function5 = np.dot(a1,a2.T)

## Function 1 - np.add (change this)

Add some explanation about the function in your own words

In [ ]:
# Example 1 - working (change this)
arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6],
        [8, 9]]

np.add(arr1, arr2)

array([[ 6.,  8.],
       [11., 13.]])

Explanation : It joined the two arrays according to the axis . Here axis = 1 because it is a 2D array.

In [ ]:
# Example 2 - working
arr1 = [[10, 12],
        [29, 54.]]

arr2 = [[51, 6],
        [85, 9]]

np.add(arr1, arr2)

array([[ 61.,  18.],
       [114.,  63.]])

Explanation : Joined arr1 and arr2 (nboth are 1D array ) and so axis = 0



Explanation about example (why it breaks and how to fix it)

operands could not be broadcast together with shapes (2,2) (2,3)
To fix this ,
np.add() -> argument dimensions should be same

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr1 = [[1, 2],
        [3, 4.]]

arr2 = [[5, 6, 7],
        [8, 9, 10]]

np.add(arr1, arr2)

ValueError: ignored

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 2 - np.subtract

Used to perform subtraction on arrays

In [ ]:
# Example 1 - working
arr = [1,2,3]
arr1 = [3,4,5]
arrsub = np.subtract(arr,arr1)
arrsub

array([-2, -2, -2])


Explanation about example: Subtracts arr1 from arr

In [ ]:
# Example 2 - working
arr = [1,2,3,4]
arr1 = [3,4,5,6]
arrsub = np.subtract(arr,arr1)
arrsub

array([-2, -2, -2, -2])

Explanation about example: Subtracts arr1 from arr

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
arr = [1,2,3,4]
arr1 = [3,4,5]
arrsub = np.subtract(arr,arr1)
arrsub

ValueError: ignored

Explanation about example (why it breaks and how to fix it) ⁉

Here , the dimensions are different , thus it breaks

Some closing comments about when to use this function: Use this function in order to perform subtraction on the matrix

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 3 - np.multiply

Used to perform multiplication of the matrices

In [ ]:
# Example 1 - working
a1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op = np.multiply(a1,a2)
op

array([[11, 24, 39, 56, 75],
       [11, 24, 39, 56, 75]])

multiplies every element in a1 matrix with its respective element in a2

In [ ]:
# Example 2 - working
a1 = np.array([[0,0,3,4,5],[1,2,3,4,5]])
a2 = np.array([[1,2,1,4,5],[1,14,3,1,5]])
op = np.multiply(a1,a2)
op

array([[ 0,  0,  3, 16, 25],
       [ 1, 28,  9,  4, 25]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a1 = np.array([[1,2,3,4,5,6],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op = np.multiply(a1,a2)
op

<ipython-input-22-4c97aca7fdbe>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[1,2,3,4,5,6],[1,2,3,4,5]])


ValueError: ignored

Explanation about example (why it breaks and how to fix it) :  a1[0] has 6 elements so the dimension of the matrix changes. We can multiply if he dimensions are same of the two matrices

Some closing comments about when to use this function.

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 4 - np.divide

Used to perform multiplication of the matrices

In [ ]:
# Example 1 - working


In [ ]:
a1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op = np.divide(a1,a2)
op

array([[0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333],
       [0.09090909, 0.16666667, 0.23076923, 0.28571429, 0.33333333]])

Explanation about example :  Divides each element in a1 by its respective corresponding element in a2

In [ ]:
# Example 2 - working
a2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a1 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op = np.divide(a1,a2)
op

array([[11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ],
       [11.        ,  6.        ,  4.33333333,  3.5       ,  3.        ]])

Explanation about example: Divides each element in a1 by its respective corresponding element in a2


In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a1 = np.array([[1,2,3,4],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[12,13,14,15]])
op = np.divide(a1,a2)
op

<ipython-input-29-44d30c6e9f67>:2: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a1 = np.array([[1,2,3,4],[1,2,3,4,5]])
<ipython-input-29-44d30c6e9f67>:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a2 = np.array([[11,12,13,14,15],[12,13,14,15]])


TypeError: ignored

Explanation about example (why it breaks and how to fix it) : There is no corresponding element in 2 cases which is causing error. The dimensions of the two matrices must be same

Some closing comments about when to use this function : Use this function in order to divide elements in matrices

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Function 5 - np.dot

Used to perform dot operation on the matrix

In [ ]:
# Example 1 - working
a1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a2 = np.array([[11,12,13,14,15],[11,12,13,14,15]])
op = np.dot(a1,a2.T)
op

array([[205, 205],
       [205, 205]])

Explanation about example: Finds dot product of the two matrices

In [ ]:
# Example 2 - working
a1 = np.array([[1,1],[4,5]])
a2 = np.array([[11,12],[13,15]])
op = np.dot(a1,a2.T)
op

array([[ 23,  28],
       [104, 127]])

Explanation about example

In [ ]:
# Example 3 - breaking (to illustrate when it breaks)
a1 = np.array([[1,2,3,4,5],[1,2,3,4,5]])
a2 = np.array([[11,12],[14,15]])
op = np.dot(a1,a2.T)
op

ValueError: ignored

Explanation about example (why it breaks and how to fix it) :

It breaks because shapes (2,5) and (2,2) not aligned: 5 (dim 1) != 2 (dim 0)

Some closing comments about when to use this function.
Use this function when to find dot product

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.


## Conclusion

In this notebook we learnt about 5 simple yet interesting functions of numpy module:


1.   function1 = np.add(a1,a2)
2.   function2 = np.subtract(a1,a2)
3.   function3 = np.multiply(a1,a2)
4.   function4 = np.divide(a1,a2)
5.   function5 = np.dot(a1,a2.T)


## Reference Links
Provide links to your references and other interesting articles about Numpy arrays:
* Numpy official tutorial : https://numpy.org/doc/stable/user/quickstart.html

In [ ]:
jovian.commit()

[jovian] Detected Colab notebook...
[jovian] jovian.commit() is no longer required on Google Colab. If you ran this notebook from Jovian, 
then just save this file in Colab using Ctrl+S/Cmd+S and it will be updated on Jovian. 
Also, you can also delete this cell, it's no longer necessary.
